apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-service-deployment
  labels:
    app: first-service
spec:
  selector:
    matchLabels:
      app: first-service
  template:
    metadata:
      labels:
        app: first-service
    spec:
      containers:
      - name: first-service
        image: first-service:latest