apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  labels:
    app: nats
spec:
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
      - name: nats
        image: nats:latest
        command: ["/nats-server"]
        args: ["--config", "nats-server.conf", "-VV"]
        ports:
        - containerPort: 4222

---
apiVersion: v1
kind: Service
metadata:
  name: nats
spec:
  selector:
    app: nats
  ports:
    - name: p4 
      protocol: TCP
      port: 4222
      targetPort: 4222
    - name: p8
      protocol: TCP
      port: 8222
      targetPort: 8222
    - name: p6 
      protocol: TCP
      port: 6222
      targetPort: 6222