apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-service
  labels:
    app: second-service
spec:
  selector:
    matchLabels:
      app: second-service
  template:
    metadata:
      labels:
        app: second-service
    spec:
      containers:
      - name: second-service
        image: second-service:latest