# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

defaults:
  run:
    working-directory: ./nestjs-mongoose

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache node_modules
        id: deps_cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ hashFiles( '**/yarn.lock' ) }}
      - name: Setup yarn
        run: npm install -g yarn
      - name: Install dependencies
        if: steps.deps_cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Run build API
        run: yarn run build:api
      - name: Run build CRON
        run: yarn run build:cron
  scan:
    runs-on: ubuntu-latest
    needs:
    - build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ hashFiles( '**/yarn.lock' ) }}
      - name: Setup yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Qodana Scan
        uses: JetBrains/qodana-action@v4.2.5
        with:
          linter: jetbrains/qodana-js
          changes: true
